name: good_dismissable
description: A polished Flutter alternative to Dismissible with cleaner swipe-to-dismiss and reveal actions for cards, lists, and inbox-style UIs.
version: 1.1.0
homepage: https://github.com/ZianFahrudy/good_dismissable
repository: https://github.com/ZianFahrudy/good_dismissable
issue_tracker: https://github.com/ZianFahrudy/good_dismissable/issues

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
